# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/github/school/wujian100/wujian100/.Xil/Vivado-5776-y7000pr/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-3
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    E:/github/school/wujian100/wujian100/soc
    E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm
  } {
      E:/github/school/wujian100/wujian100/soc/utils/hdl/ahb_enum.sv
      E:/github/school/wujian100/wujian100/soc/ahb_iopmp.sv
      E:/github/school/wujian100/wujian100/soc/ahb_mailbox.sv
      E:/github/school/wujian100/wujian100/soc/apb_pmu.sv
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/me_iddmm_top.sv
      E:/github/school/wujian100/wujian100/soc/utils/hdl/ram_sp.sv
    }
      rt::read_verilog -include {
    E:/github/school/wujian100/wujian100/soc
    E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm
  } {
      E:/github/school/wujian100/wujian100/soc/E902_20191018.v
      E:/github/school/wujian100/wujian100/soc/sim_lib/PAD_DIG_IO.v
      E:/github/school/wujian100/wujian100/soc/sim_lib/PAD_OSC_IO.v
      E:/github/school/wujian100/wujian100/soc/sim_lib/STD_CELL.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/ahb/ahb2fifo_slave_core.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/ahb/ahb_fifo.v
      E:/github/school/wujian100/wujian100/soc/ahb_matrix_top.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/ahb/ahb_rsa2048.v
      E:/github/school/wujian100/wujian100/soc/aou_top.v
      E:/github/school/wujian100/wujian100/soc/apb0.v
      E:/github/school/wujian100/wujian100/soc/apb0_sub_top.v
      E:/github/school/wujian100/wujian100/soc/apb1.v
      E:/github/school/wujian100/wujian100/soc/apb1_sub_top.v
      E:/github/school/wujian100/wujian100/soc/clkgen.v
      E:/github/school/wujian100/wujian100/soc/common.v
      E:/github/school/wujian100/wujian100/soc/core_top.v
      E:/github/school/wujian100/wujian100/soc/dmac.v
      E:/github/school/wujian100/wujian100/soc/dummy.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/ahb/fifo_rsa2048_ctrl.v
      E:/github/school/wujian100/wujian100/soc/gpio0.v
      E:/github/school/wujian100/wujian100/soc/ls_sub_top.v
      E:/github/school/wujian100/wujian100/soc/matrix.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/r2mm/me_top.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/mm_iddmm_sub.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/r2mm/mm_r2mm.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/r2mm/mm_r2mm_2n.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/mmp_iddmm_addend.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/mmp_iddmm_addfirst.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/mmp_iddmm_ctrl.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/mmp_iddmm_mul128.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/mmp_iddmm_pe.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/mmp_iddmm_shift.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/mmp_iddmm_sp.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/mult.v
      E:/github/school/wujian100/wujian100/soc/pdu_top.v
      E:/github/school/wujian100/wujian100/soc/pwm.v
      E:/github/school/wujian100/wujian100/soc/retu_top.v
      E:/github/school/wujian100/wujian100/soc/rtc.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_p12adder256_3_2.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_p1adder129.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_ram.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_vedic_128bit.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_vedic_16bit.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_vedic_32bit.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_vedic_4bit.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_vedic_64bit.v
      E:/github/school/wujian100/wujian100/soc/RSA/rtl/iddmm/common/simple_vedic_8bit.v
      E:/github/school/wujian100/wujian100/soc/sms.v
      E:/github/school/wujian100/wujian100/soc/smu_top.v
      E:/github/school/wujian100/wujian100/soc/tim.v
      E:/github/school/wujian100/wujian100/soc/tim1.v
      E:/github/school/wujian100/wujian100/soc/tim2.v
      E:/github/school/wujian100/wujian100/soc/tim3.v
      E:/github/school/wujian100/wujian100/soc/tim4.v
      E:/github/school/wujian100/wujian100/soc/tim5.v
      E:/github/school/wujian100/wujian100/soc/tim6.v
      E:/github/school/wujian100/wujian100/soc/tim7.v
      E:/github/school/wujian100/wujian100/soc/usi0.v
      E:/github/school/wujian100/wujian100/soc/usi1.v
      E:/github/school/wujian100/wujian100/soc/wdt.v
      E:/github/school/wujian100/wujian100/soc/wujian100_open_top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top wujian100_open_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting true
    rt::set_parameter generateDataflowBusNetlist true
    rt::set_parameter dataFlowViewInElab true
    rt::set_parameter busViewFixBrokenConnections true
    rt::set_parameter dfvSettings "min_width=16"
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/github/school/wujian100/wujian100/.Xil/Vivado-5776-y7000pr/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
